### PR TITLE
ci:  Remove useless steps on main workflow

### PR DESCRIPTION
**Pull request by tungbq**
Closes: #9

### CODE REVIEW

**Comment by apomalyn** [comment]
Thank you @tungbq! Wasn't expecting anyone to do an issue on this repo 😅 
I'm going to add a few things to this PR if you don't mind then I will merge it 😄
I want to improve the workflow execution conditions 😄

**Comment by tungbq** [comment]
> Thank you @tungbq! Wasn't expecting anyone to do an issue on this repo 😅 I'm going to add a few things to this PR if you don't mind then I will merge it 😄 I want to improve the workflow execution conditions 😄

Sorry for the inconvenience. Thanks @apomalyn for letting me know. I will close this PR, then let you work on the other one with your current improvement in hand.

**Comment by apomalyn** [comment]
No no! It's not an inconvenience! Let me reopen it, I will merge it in a later date 😄

**Comment by tungbq** [comment]
> No no! It's not an inconvenience! Let me reopen it, I will merge it in a later date 😄

Okay, got it. Please feel free to add or improve this PR. Also let me know if you need any help 😄

**Pull request merged**
